### ISSUE TITLE
Right arrow after selecting recording group leads to crash

### ISSUE THREAD

**Issue by faginbagin** [bennettpeter/android-MythTV-Leanfront#22] opened 2021-12-12 20:47 UTC
First, I want to say that I really like leanfront and you've done a great job documenting it. It works well on my Fire TV 4k connected to a v29 backend, playing 1080i and 720p content smoothly, which is more that I can say for my other project, trying to get an rPi4 to playback mythtv recordings smoothly.

Anyway, I did discover what I think is a bug discovered by my trying to figure out how to use leanfront without fully reading your documentation. After navigating to a recording group on the left hand side, I assumed a right arrow would take me to the right hand side of the screen and the list of titles. But it didn't. Instead the app locked up and after a few seconds kicked me out of leanfront and back to the list of apps. I eventually figured out that the expected behavior is to press the Enter key, not the right arrow. However, it seems to me that a right arrow shouldn't cause leanfront to crash. The crash is consistently reproducible with 20211206-leanfront-release-v0-308-gdfbe0f0.apk and a v29 backend. My guess is it may be similarly reproduceable with any version of backend. If not, I'll be happy to provide logs.

**Comment by bennettpeter** [comment] 2021-12-12 22:13
I just retested to make sure, it works fine on both v31 and v32 (master). In the main screen with the list of recording groups on the left, right arrow takes you to the right hand side of the screen and you can arrow through the list of titles. Enter on the recording group does something different. It takes you to the page for that recording group and displays the shows down the left and episodes on the right. There you can use either enter or right arrow to get to the right hand side.

I don't have a v29 backend to test on. I assume that there is an api call that either is not implemented on v29 or returns something different from the newer versions.

If you can send me a log I may be able to figure it out.

```
adb connect <fire stick ip address>
adb logcat | tee tmp/android.log

```
Start up leanfront and cause crash
control-c after the crash has happened and forward me the log (pastebin).

**Comment by faginbagin** [comment] 2021-12-13 18:24
Here's a log I captured from one of two firetv sticks a few days ago:
https://drive.google.com/file/d/1arTxRPwheIW6iv1OCWTq1AhAljytM180/view?usp=sharing
Unfortunately, that stick is now with my sister.

I set up the second stick today, and I can't reproduce the crash with this one. Both sticks are configured to talk to the same backend, so I don't know why one crashed consistently and the second one doesn't. Both sticks were bought this past Cyber Monday, so they should be identical. I did capture their MAC addresses and the one that's crashing starts with a0:d2:b1 while the other starts with b4:e4:54. Maybe there's a hint there w.r.t hardware firmware differences or maybe there's some subtle difference in the way I configured them.

If the log does indicate a bug, I will retrieve the problematic stick from my sister so I can test any fixes on both sticks.

**Comment by bennettpeter** [comment] 2021-12-13 21:08
I cannot see anything in the log that would explain your crashes. There seems to have been "application not responding" errors. Is that what you saw? Many of them seem to have happened around 11:40 PM - 11:47 PM.

**Comment by faginbagin** [comment] 2021-12-13 21:40
Yes, it would hang and then after several seconds return to the home screen. And, yes, the timestamps sound right. I'll get the stick back and play with it more. Maybe it was a fluke that won't repeat after it's been power cycled a few times. If I can reproduce it, is the log I sent the type you want to see? I.e. of the "adb logcat" variety as opposed to the "adb logcat lfe:D *:S" variety?

**Comment by faginbagin** [comment] 2021-12-13 21:49
One possible explanation. When the crashes happened, the backend was behind a powerline adapter. I recently moved and am still ironing out LAN and antenna issues. I have since been able to move the backend so it's in a better location in my LAN. Maybe latency in the powerline connection to the LAN was the root cause because the backend took too long to respond to leanfront and android killed what it thought was an unresponsive app? If so, then a firetv stick with a marginal WiFi connection could have the same problem?

**Comment by bennettpeter** [comment] 2021-12-13 22:46
The "adb logcat" is best as it has everything. If you create a logcat with the problem, let me know at what time it occurred so I can try to find the appropriate part of the log.

Slow network should not cause this. All network communications are in a separate thread from the user interface. However anything is possible.

**Comment by faginbagin** [comment] 2021-12-22 00:02
So, I can duplicate the crash with both of my fire tv sticks. Here's a log from what I call the first fire tv stick, because it's the first one I set up. It's the one whose MAC start with b4:e4:54.
https://drive.google.com/file/d/1mtebc0jvWX3UtnYGN4To613JSFUOAhBD/view?usp=sharing
THe crash happened shortly before 18:45:39, and unline the other log file which covered more than one crash. I stopped logging shortly after one crash that took me back to the stick's home screen. So far, the easiest way I've found to consistently reproduce the crash is to go to leanffront's Tools -> Settings -> Program List Options, then navigate a few items without changing anything, followed by pressing the back button twice which should take me back to Tools. There's almost always a lag with no indication it's leaving Settings. Then I press the down arrow twice to see if the back button press took. Leanfront briefly returns to the main screen and then I find myself back at the stick's home screen. It feels like I'm hitting a race condition. Hope this gives you enough info to reproduce and hopefully fix.

**Comment by bennettpeter** [comment] 2021-12-22 15:49
This is a strange one. I tried your sequence but I do not get the error. After pressing back the second time I get to the program list and I can navigate in there as normal. I have not seen this type of error before.

These seem to be the relevant messages in the log

_12-21 18:45:31.312   610   651 I InputDispatcher: Application is not responding: AppWindowToken{60261b4 token=Token{f042ec6 ActivityRecord{123dca1 u0 org.mythtv.leanfront/.ui.MainActivity t66}}}.  It has been 5003.4ms since event, 5001.8ms since wait started.  Reason: Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.
....
12-21 18:45:31.517  8705  8711 I art     : Wrote stack traces to '/data/anr/traces.txt'_

Please can you get me the traces.txt file. After getting the error, run this:

```
adb connect <fire stick ip address>
adb pull /data/anr/traces.txt
adb disconnect
```
Peter

**Comment by faginbagin** [comment] 2021-12-22 17:33
I have added traces-1222.txt and firetv1-v29-1222.log to the following drive folder, which also has the older log files:
https://drive.google.com/drive/folders/1mtT77n88n_CWH6vWnmCb-37zktPtsk3r?usp=sharing
Hope they help

**Comment by faginbagin** [comment] 2021-12-22 17:43
Just in case the sequence wasn't clear, I press up or down arrow a couple of times almost immediately after pressing the back button twice. I think if I didn't do that, leanfront might not crash. But doing it is my natural response to no feedback to the second back button press. Although, I just repeated the test without pressing anything after the second back button press, and it crashes.

Tried it a third time where I paused 5 seconds before pressing back a second time. This time it didn't crash but did take me back to the All recording group, not the Tools menu, as I think it should have done. I didn't catch any logs, just playing around to see what's what. I think the fact it didn't crash if I paused between back presses, confirms a race condition at play when it does crash.

**Comment by bennettpeter** [comment] 2021-12-23 15:00
I still cannot recreate this. There is a deadlock accessing the settings when refreshing the program list.  It is in the internal code of Android and it is not clear what is happening. I have made some changes to the settings update in the hopes that this solves it. Please can you test the new version and let me know if there is any difference. 20211223-leanfront-v0-311-g2e2dc2a.apk in the "Trial Versions" directory on https://dl.orangedox.com/pCBmBm .

**Comment by faginbagin** [comment] 2021-12-23 16:46
It's too bad you can't reproduce it, when it's so easy for me to do it. Suggests it's something to do with v29. Anyway, there are two more files in:
https://drive.google.com/drive/folders/1mtT77n88n_CWH6vWnmCb-37zktPtsk3r?usp=sharing
firetv2-v29-1223.log and traces-1223.txt

I probably won't be able to test another version until next week, so enjoy the Holidays!

**Comment by bennettpeter** [comment] 2021-12-26 19:41
I have made another change. The new build is 20211226-leanfront-v0-312-gbe77634.apk in the "Trial Versions" Directory. When you have a chance, please test this and let me know if it solves the problem.

**Comment by faginbagin** [comment] 2021-12-26 21:20
Afraid it didn't help. The latest log & trace are: firetv2-v29-312-1226.log, traces-312-1226.txt in:
https://drive.google.com/drive/folders/1mtT77n88n_CWH6vWnmCb-37zktPtsk3r?usp=sharing

**Comment by bennettpeter** [comment] 2021-12-27 18:00
I will build a V29 backend to try and reproduce this. That will have to be next week. In the meantime, if you have any other ways of creating the error or other details, please log them here. As things stand, if it only happens after going into settings, that should not cause you too much of a problem since settings will not normally be used while watching.

**Comment by faginbagin** [comment] 2021-12-28 23:41
I will also try to attack the problem from the other direction by setting up a v31 backend migrating my v29 database to it. Like you, I probably won't have it working until next week. Things are definitely more stable with 312. Before I installed it on my sister's firetv, I couldn't even navigate to her video library without crashing. Now I can get there and play content from the video library. But there's at least one problem with subtitles. I'm creating a separate issue for that.

**Comment by bennettpeter** [comment] 2021-12-29 14:59
In 312 I also fixed a bug where it was crashing when it found a zero size for the storage groups. That is something I found a few days ago before you logged this error. Is your sister's system displaying the percentage disk utilization at the top of the main screen next to the magnifying glass? If not - then that could be what the problem was. Perhaps her backend does not give the expected response to the storage group statistics.

**Comment by faginbagin** [comment] 2021-12-29 16:00
Both our firetv sticks show correct disk usage precentages. I'll get back to you w.r.t a sample. I need to refresh my command line fu on either ffmpeg or mkvtoolnix.

**Comment by bennettpeter** [comment] 2021-12-29 16:52
Extract first 10 minutes, for example:
```
mkvmerge \
--split parts:00:00:00-00:10:00  \
-o output.mkv \
input.mkv

```

**Comment by faginbagin** [comment] 2021-12-30 05:28
I triggered another crash after playing the video clip for issue 23. I was pressing the back button, trying to get out of my video library to the top and was planning to get to the recently viewed menu. So, the crash is not limited to Settings. See 1230-crash.log and 1230-traces.txt in the usual drive folder.

**Comment by bennettpeter** [comment] 2021-12-30 15:15
This crash was in the same place as the others. It occurs while refreshing the program list, which happens both after settings and after playback.

I have created a debug build in the "Debug Versions" directory, called 20211230-leanfront-debug-v0-313-gb587214.apk. If you create the crash in the debug version, the traces.txt should contain more information to help me debug.

I saw a bug in your latest log. If the fire stick loses the backend connection for some reason and then regains it, there is an endless loop of failing messages to the backend. This only happens on a prior to v30 backend. This is fixed in the 313 debug build.

**Comment by faginbagin** [comment] 2022-01-01 16:45
313 crashed before I could even play anything. FWIW, when I install a new apk, I usually clear the cache and restart the fire stick after installing and before running leanfront. And that's what I did this time.

After getting the main leanfront screen, I cursored right to get to the first recording and then it crashed. The logs are: 0101-crash.log 0101-traces.txt

I don't know if it's relevant, since I never got the opportunity to play anything, but the first recording is a very old NuppelVideo ,nuv recording, which I was going to see if it could be played.

**Comment by bennettpeter** [comment] 2022-01-01 21:57
Looking at the trace, it dies in a random place during screen reload. I do not get anything useful from it. The ANR (Application Not Responding) seems to kill the process if it takes more than 5 seconds to load.

Perhaps you have a very large number of recordings and videos, so that it is taking too long to refresh the screen. How many recordings and videos do you have? Would your sister also have a very large number?

**Comment by bennettpeter** [comment] 2022-01-01 22:55
Not a solution - but try waiting 5 seconds after you get to the program list, before hitting any buttons. If the crash is caused by excessive number of recordings and videos, this should avoid the problem. If this is the case I will fix it by making the screen reload asynchronous. Having to wait 5 seconds each time would be a ridiculous restriction.

**Comment by faginbagin** [comment] 2022-01-02 16:02
What's' a large number? I've got over 550 recordings. My sister has over 2800 recordings. Our video libraries are similar in size, over 6300 each. Plus I've got an additional 300 test clips, most from avsforum I use to calibrate my TVs. I know there are folks on mythtv-users who have much more, based on how much disk space they mention having, although maybe our stuff is more compressed than theirs. Can it be that I've got a larger media library than any other leanfront users, so far?

I played it even safer, waiting at least 10 seconds between button presses and it didn't crash.

**Comment by bennettpeter** [comment] 2022-01-02 18:42
I have 1398 recordings and 1388 videos. So you have far more videos than me Perhaps the number of videos is the problem, or the number of recordings in your sister's case. I don't know what other leanfront users have or how quickly they hit a button while the screen loads. I also did not realize that 5 seconds was an absolute cutoff for the "Application Not Responding" error.

If you go into a recording group or a video directory that has fewer that 1388 videos, you should not see the error after that. Your sister had worse problems perhaps because she has 2800 recordings, so even when she goes into a recording group she may have the problem.

I have an external drive with another 9000 videos. If I add those I will have a good test setup to see if that causes the problem, so that I can fix it.

**Comment by faginbagin** [comment] 2022-01-03 04:20
I was able to reproduce the crash with a v31 backend that's using my v29 database migrated to a different machine. Hopefully that means you should be able to reproduce the crash when you add your external drive. The logs are named 0102-v31-crash.log 0102-v31-traces.txt

**Comment by faginbagin** [comment] 2022-01-04 18:55
I've also got a 4k, not a 4k max:

$ adb shell getprop | grep ro.product.model
[ro.product.model]: [AFTMM]
$ adb shell getprop | grep ro.vendor.build
[ro.vendor.build.date]: [Wed Oct 13 05:11:05 UTC 2021]
[ro.vendor.build.date.utc]: [1634101865]
[ro.vendor.build.fingerprint]: [Amazon/mantis/mantis:6.0/NS6281/4061N:user/amz-p,release-keys]

I'm more likely to see a crash if I clear the cache and restart the device. And I see it when I first go in, just trying to navigate to a recording or video of interest, waiting 10 or more seconds between button presses, especially right or OK, helps.

Other things that might be factors in my environment:
- 5 recording groups in 2 storage groups/partitions
-  Video directories are often 3 deep, 7 top level directories split amongst 3 storage groups/partitions.
-  I've got separate top level directories for personal videos, test clips, TV shows and movies, long running TV shows with more than 100 episodes are in separate season directories.
- It can take several seconds for a remote frontend to get into the video library. I just timed it on a acer revo 3610 using 2.4 Ghz 802.11n and that took over 15 seconds. Both it and the fire stick are about 35' from the router, an Asus RT-AX3000 running merlin firmware. The fire stick has a clear line of sight to the router, better than the 3610.
- My database is on a sata ssd, not an nvme. The CPU is a  i3-3220. It also provides off-site backup service via rsync for my sister's zoneminder system, receiving any new events every 5 minutes which might have some impact on the network.

Hope that helps.

**Comment by bennettpeter** [comment] 2022-01-04 22:49
When you say "clearing the cache" - is that clearing the cache for the leanfront application in the settings? I have never cleared that cache so perhaps that is related to the problem. Clearing the cache is going to make subsequent runs slower while it gets reloaded.

If you avoid clearing the cache, does the problem eventually resolve itself?

Slowness of the network or of MythTV should not be related. The download from MythTV already takes place in a separate thread. The reload of the display from the fire stick local storage seems to be what is causing the problem.

The error is ANR (Application Not Responding). The android device is supposed to display a dialog saying the application is not responding and ask you if you wish to continue. I don't know why it is not doing that, instead just killing the app.

I have not found an easy way to load the data in a separate thread as all display output has to be in one thread. I am still trying to figure that out.

**Comment by faginbagin** [comment] 2022-01-05 17:33
Yes, clearing leanfront's cache from the firetv's Settings -> Applications -> Manage Installed Applications -> MythTV LeanBack Frontend. I have made a point of doing this when I install a new version or when I change backends. It does get better over time, but it can still crash if I don't wait long enough. I'm getting better at recognizing the visual cues and minimizing the chances of a crash, but it still happens long after the cache is cleared.

**Comment by bennettpeter** [comment] 2022-01-06 20:48
I have created a package in "Trial Versions" : 20220106-leanfront-v0-316-g925df02.apk

This now has the building of the main screen in a separate thread from the UI. It is lightly tested so there may be bugs. The old code is still present and will need to be removed if this is OK. Let me know if this solves the problem.

**Comment by faginbagin** [comment] 2022-01-07 00:54
Preliminary results are good. It passed the Tools -> Settings -> Program List test and I was able to navigate fairly quickly around recordings an videos without triggering a crash. And, this was after clearing the cache and restarting the device.

FYI, I had also changed from dns name to ip addr while the previous debug version was installed (20211230-leanfront-debug-v0-313-gb587214.apk). It may have helped a little, but I was still able to get that version to crash. So, I'm wondering whether to try going back to dns name with this trial version.

I did notice one oddity. After going into videos and then backing out, I found myself thrown into my default recording group with a recording selected that I had played before going into videos. Maybe it was a fluke. I'll try to reproduce it in the next few days.

**Comment by bennettpeter** [comment] 2022-01-07 14:12
I would say go back to your normal setup with the dns. That should work and I need to fix it if it does not work. On thinking again, the problem that I have had is probably caused when I have an IP address in mythtv-setup that is unreachable from the fire stick, for example it is on another network.

**Comment by faginbagin** [comment] 2022-01-08 00:35
I have made the ip to name switch and leanfront is behaving. I still see the occasional oddity where I get kicked back to where I was a few steps earlier, but it's not crashing and it's not hard to get to where I want to go.

**Comment by bennettpeter** [comment] 2022-01-08 01:03
I did find a bug where you get kicked backe extra steps. The details page was crashing. That mainly happens if you stop playback less than 10 seconds after starting playback or less than 10 seconds after a skip. I have a fix in for the next build. It should not affect normal watching but you may see it if you are testing by playing short bits then exiting.

**Comment by bennettpeter** [comment] 2022-01-08 16:25
There is a new package in Trial Versions: 20220108-leanfront-v0-322-gbac7f03.apk

* bac7f03 2022/01/08 Peter Bennett : Playback: Enable screen saver during pause.                           
* d5da0bb 2022/01/08 Peter Bennett : Fix for fire stick resume after app goes into background              
* 9981bad 2022/01/07 Peter Bennett : synchronize VideoDbHelper creation                                    
* b927d47 2022/01/07 Peter Bennett : Fix for leaked SQL cxonnections.                                      
* 3540745 2022/01/07 Peter Bennett : Fix for occasional crash of details screen after playback             
* 0562da1 2022/01/07 Peter Bennett : Add disk usage back to main screen

**Comment by bennettpeter** [comment] 2022-01-13 17:34
All changes have now been incorporated in release version 20211206-leanfront-release-v0-308-gdfbe0f0.apk

**Closed by bennettpeter** 2022-01-13 17:34 UTC
